# Generated by Django 6.0.3 on 2026-04-08 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_user_gender_employee_mobile'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChemicalUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_consumed', models.DecimalField(decimal_places=4, max_digits=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('chemical', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usage_logs', to='core.chemical')),
                ('media_preparation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chemical_usage_logs', to='core.mediapreparation')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='MediaChemicalRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_required', models.DecimalField(decimal_places=4, help_text="Amount of chemical required per litre of media (in chemical's own unit)", max_digits=10)),
                ('chemical', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='media_requirements', to='core.chemical')),
                ('media_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chemical_requirements', to='core.mediatype')),
            ],
            options={
                'ordering': ['media_type', 'chemical'],
                'unique_together': {('media_type', 'chemical')},
            },
        ),
    ]
