# Generated by Django 6.0.3 on 2026-04-27 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_chemicalusagelog_mediachemicalrequirement'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserOTP',
        ),
        migrations.RemoveField(
            model_name='user',
            name='employee_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='user',
            name='mobile_number',
        ),
        migrations.RemoveField(
            model_name='user',
            name='profile_picture',
        ),
    ]
