# Generated by Django 6.0.3 on 2026-05-05 06:13

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_delete_userotp_remove_user_employee_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockSolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('remaining_volume', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('unit', models.CharField(default='mL', max_length=20)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MediaStockUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume_consumed', models.DecimalField(decimal_places=2, max_digits=10)),
                ('media_preparation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_usages', to='core.mediapreparation')),
                ('stock_solution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='media_usage_logs', to='core.stocksolution')),
            ],
        ),
        migrations.CreateModel(
            name='StockSolutionPreparation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume_prepared', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('prepared_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_preparations', to=settings.AUTH_USER_MODEL)),
                ('stock_solution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='preparations', to='core.stocksolution')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockSolutionChemicalUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_consumed', models.DecimalField(decimal_places=4, max_digits=10)),
                ('chemical', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_usage_logs', to='core.chemical')),
                ('preparation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chemical_usages', to='core.stocksolutionpreparation')),
            ],
        ),
    ]
