# Generated by Django 6.0.3 on 2026-05-18 05:42

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_user_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contaminationmonitoring',
            name='area',
        ),
        migrations.RemoveField(
            model_name='contaminationmonitoring',
            name='recorded_by',
        ),
        migrations.RemoveField(
            model_name='contaminationreport',
            name='operator',
        ),
        migrations.RemoveField(
            model_name='contaminationreport',
            name='variety',
        ),
        migrations.RemoveField(
            model_name='greenhouse',
            name='findings',
        ),
        migrations.RemoveField(
            model_name='greenhouse',
            name='recorded_by',
        ),
        migrations.RemoveField(
            model_name='greenhouse',
            name='variety',
        ),
        migrations.RemoveField(
            model_name='growthroom',
            name='recorded_by',
        ),
        migrations.RemoveField(
            model_name='growthroom',
            name='variety',
        ),
        migrations.RemoveField(
            model_name='inoculationroom',
            name='operator',
        ),
        migrations.RemoveField(
            model_name='inoculationroom',
            name='variety',
        ),
        migrations.CreateModel(
            name='HardeningLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seedlings_transplanted', models.IntegerField(default=0, help_text='Seedling Transplant in Green House (Nos)')),
                ('seedlings_died', models.IntegerField(default=0, help_text='Seedling Dried in Green House (Nos)')),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('variety', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.variety')),
            ],
            options={
                'ordering': ['-date'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InitiationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bottles_inoculated', models.IntegerField(default=0, help_text='Meristem Tissue Inoculated (No. of Bottles)')),
                ('contaminated_bottles', models.IntegerField(default=0, help_text='Contaminated Tubes (Nos)')),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('variety', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.variety')),
            ],
            options={
                'ordering': ['-date'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MultiplicationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cycle_number', models.IntegerField(choices=[(1, 'Ist'), (2, 'IInd'), (3, 'IIIrd'), (4, 'IVth'), (5, 'Vth')])),
                ('bottles_produced', models.IntegerField(default=0, help_text='No. of Bottles')),
                ('contaminated_bottles', models.IntegerField(default=0, help_text='Contaminated Bottles (Nos)')),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('variety', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.variety')),
            ],
            options={
                'ordering': ['-date'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RootingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('basal_bottles', models.IntegerField(default=0, help_text='Basal (No. of Bottles)')),
                ('rooting_bottles', models.IntegerField(default=0, help_text='Rooting (No. of Bottles)')),
                ('contaminated_bottles', models.IntegerField(default=0, help_text='Contaminated Bottles (Nos)')),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('variety', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.variety')),
            ],
            options={
                'ordering': ['-date'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TransplantationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seedlings_transplanted', models.IntegerField(default=0, help_text='Seedling Transplant in Field (Nos)')),
                ('seedlings_died', models.IntegerField(default=0, help_text='Seedling Dried in Field (Nos)')),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('variety', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.variety')),
            ],
            options={
                'ordering': ['-date'],
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Area',
        ),
        migrations.DeleteModel(
            name='ContaminationMonitoring',
        ),
        migrations.DeleteModel(
            name='ContaminationReport',
        ),
        migrations.DeleteModel(
            name='FindingType',
        ),
        migrations.DeleteModel(
            name='Greenhouse',
        ),
        migrations.DeleteModel(
            name='GrowthRoom',
        ),
        migrations.DeleteModel(
            name='InoculationRoom',
        ),
    ]
