# Generated by Django 6.0.3 on 2026-05-18 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_contaminationmonitoring_area_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='mediachemicalrequirement',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='mediachemicalrequirement',
            name='chemical',
        ),
        migrations.RemoveField(
            model_name='mediachemicalrequirement',
            name='media_type',
        ),
        migrations.RemoveField(
            model_name='mediapreparation',
            name='media_type',
        ),
        migrations.RemoveField(
            model_name='mediapreparation',
            name='prepared_by',
        ),
        migrations.RemoveField(
            model_name='mediastockusage',
            name='media_preparation',
        ),
        migrations.RemoveField(
            model_name='mediastockusage',
            name='stock_solution',
        ),
        migrations.CreateModel(
            name='StockSolutionRecipeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_per_unit', models.DecimalField(decimal_places=4, help_text="Amount of chemical required per unit of stock solution (in chemical's own unit)", max_digits=10)),
                ('chemical', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_recipes', to='core.chemical')),
                ('stock_solution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_items', to='core.stocksolution')),
            ],
            options={
                'ordering': ['stock_solution', 'chemical'],
                'unique_together': {('stock_solution', 'chemical')},
            },
        ),
        migrations.DeleteModel(
            name='ChemicalUsageLog',
        ),
        migrations.DeleteModel(
            name='MediaChemicalRequirement',
        ),
        migrations.DeleteModel(
            name='MediaType',
        ),
        migrations.DeleteModel(
            name='MediaPreparation',
        ),
        migrations.DeleteModel(
            name='MediaStockUsage',
        ),
    ]
