# Generated by Django 6.0.3 on 2026-05-18 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_mediachemicalrequirement_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocksolution',
            name='base_volume',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=10),
        ),
    ]
