# Generated by Django 6.0.3 on 2026-06-15 10:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_expensecategory_chemical_unit_price_expense'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManpowerExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveSmallIntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')])),
                ('year', models.PositiveSmallIntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recorded_salaries', to=settings.AUTH_USER_MODEL)),
                ('technician', models.ForeignKey(limit_choices_to={'role': 'technician'}, on_delete=django.db.models.deletion.PROTECT, related_name='salary_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Manpower Expense',
                'verbose_name_plural': 'Manpower Expenses',
                'ordering': ['-year', '-month', 'technician'],
                'unique_together': {('technician', 'month', 'year')},
            },
        ),
    ]
