# Generated by Django 6.0.3 on 2026-06-15 10:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_manpower_expense'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manpowerexpense',
            options={'ordering': ['technician'], 'verbose_name': 'Manpower Expense', 'verbose_name_plural': 'Manpower Expenses'},
        ),
        migrations.RenameField(
            model_name='manpowerexpense',
            old_name='amount',
            new_name='monthly_salary',
        ),
        migrations.AlterUniqueTogether(
            name='manpowerexpense',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='manpowerexpense',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='manpowerexpense',
            name='technician',
            field=models.OneToOneField(limit_choices_to={'role': 'technician'}, on_delete=django.db.models.deletion.PROTECT, related_name='salary_record', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='manpowerexpense',
            name='month',
        ),
        migrations.RemoveField(
            model_name='manpowerexpense',
            name='year',
        ),
    ]
