# Generated by Django 6.0.3 on 2026-06-16 16:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_manpower_expense_v2'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('location_type', models.CharField(choices=[('company_farm', 'Company Farm'), ('contract_farm', 'Contract Farm')], default='company_farm', max_length=30)),
                ('district', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(default='Uttar Pradesh', max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Field Location',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('village', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('aadhar_number', models.CharField(blank=True, max_length=20)),
                ('quality_score', models.DecimalField(decimal_places=1, default=0.0, help_text='Score 0–10 based on seed purity and germination quality.', max_digits=4)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('primary_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='farmers', to='core.fieldlocation')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Plot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plot_number', models.CharField(max_length=30)),
                ('area_acres', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('notes', models.TextField(blank=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plots', to='core.fieldlocation')),
            ],
            options={
                'ordering': ['location', 'plot_number'],
                'unique_together': {('location', 'plot_number')},
            },
        ),
        migrations.CreateModel(
            name='SeedLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lot_id', models.CharField(help_text='e.g. BR-2026-001', max_length=50, unique=True)),
                ('stage', models.CharField(choices=[('breeder', 'Breeder Seed'), ('foundation', 'Foundation Seed'), ('certified', 'Certified Seed'), ('commercial', 'Commercial Seed')], max_length=20)),
                ('lab_batch_reference', models.CharField(blank=True, help_text='Reference to the LabNest TC batch (e.g. TC-2026-045)', max_length=100)),
                ('quantity_kg', models.DecimalField(decimal_places=3, max_digits=12)),
                ('season_year', models.IntegerField(help_text='The crop year this lot belongs to.')),
                ('status', models.CharField(choices=[('in_field', 'In Field'), ('harvested', 'Harvested'), ('dispatched', 'Dispatched'), ('rejected', 'Rejected')], default='in_field', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_seed_lots', to=settings.AUTH_USER_MODEL)),
                ('farmer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seed_lots', to='core.farmer')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seed_lots', to='core.fieldlocation')),
                ('parent_lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_lots', to='core.seedlot')),
                ('plot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seed_lots', to='core.plot')),
                ('variety', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='seed_lots', to='core.variety')),
            ],
            options={
                'verbose_name': 'Seed Lot',
                'ordering': ['-season_year', 'stage', 'lot_id'],
            },
        ),
        migrations.CreateModel(
            name='SeedLotTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txn_type', models.CharField(choices=[('dispatch', 'Dispatched to Farmer'), ('harvest', 'Harvest Received from Farmer'), ('status_change', 'Status Changed'), ('transfer', 'Lot Transferred')], max_length=20)),
                ('quantity_kg', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('notes', models.TextField(blank=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('farmer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.farmer')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.fieldlocation')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='field_transactions', to=settings.AUTH_USER_MODEL)),
                ('seed_lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='core.seedlot')),
            ],
            options={
                'verbose_name': 'Seed Lot Transaction',
                'ordering': ['-recorded_at'],
            },
        ),
    ]
