# Generated by Django 6.0.3 on 2026-06-16 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_fieldlocation_farmer_plot_seedlot_seedlottransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='transplantationlog',
            name='field_lot_id',
            field=models.CharField(blank=True, help_text='Optional: Automatically create a FieldLink Breeder Lot with this ID', max_length=50),
        ),
    ]
