# Generated by Django 6.0.3 on 2026-06-17 06:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_transplantationlog_field_lot_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='transplantationlog',
            name='farmer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transplantation_logs', to='core.farmer'),
        ),
        migrations.AddField(
            model_name='transplantationlog',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transplantation_logs', to='core.fieldlocation'),
        ),
    ]
