# Generated by Django 6.0.3 on 2026-06-24 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_transplantationlog_farmer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer',
            name='grower_code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
