# Generated by Django 6.0.3 on 2026-06-25 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_farmer_grower_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='plot',
            name='boundaries',
            field=models.JSONField(blank=True, help_text='GeoJSON polygon representing the plot boundary.', null=True),
        ),
        migrations.AddField(
            model_name='plot',
            name='centroid_lat',
            field=models.DecimalField(blank=True, decimal_places=7, help_text='Latitude of the plot center point.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='plot',
            name='centroid_lng',
            field=models.DecimalField(blank=True, decimal_places=7, help_text='Longitude of the plot center point.', max_digits=10, null=True),
        ),
    ]
