# Generated by Django 6.0.3 on 2026-06-25 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_plot_boundaries_plot_centroid_lat_plot_centroid_lng'),
    ]

    operations = [
        migrations.AddField(
            model_name='seedlot',
            name='custom_coordinates',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='seedlot',
            name='custom_plot_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
