# Generated by Django 6.0.3 on 2026-07-03 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_seedlot_custom_coordinates_seedlot_custom_plot_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('employee_code', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('region', models.CharField(blank=True, help_text='Territory or zone managed by this field manager (e.g. Telangana Zone).', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Field Manager',
                'verbose_name_plural': 'Field Managers',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='seedlot',
            name='status',
            field=models.CharField(choices=[('in_field', 'In Field'), ('harvested', 'Harvested'), ('dispatched', 'Dispatched'), ('sold', 'Sold'), ('rejected', 'Rejected')], default='in_field', max_length=20),
        ),
        migrations.AddField(
            model_name='farmer',
            name='field_manager',
            field=models.ForeignKey(blank=True, help_text='The field manager responsible for supervising this farmer.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='farmers', to='core.fieldmanager'),
        ),
    ]
