# Generated by Django 6.0.3 on 2026-07-05 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_add_field_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_onboarded',
            field=models.BooleanField(default=False, help_text='Set to True after the user selects their role on first login.'),
        ),
    ]
